### ISSUE TITLE
In getBlockLocations, Network Location is null [map-reduce task]

### ISSUE THREAD

**Issue by zhouhanc** [Rice-Comp413-2016/RDFS#75]
Network Location is not properly set, and as a result the map-reduce client throws an exception.

Stacktrace from map-reduce client:
```

16/11/16 19:43:40 INFO client.RMProxy: Connecting to ResourceManager at /0.0.0.0:8032
16/11/16 19:43:41 INFO input.FileInputFormat: Total input paths to process : 1
16/11/16 19:43:41 INFO mapreduce.JobSubmitter: Cleaning up the staging area /tmp/hadoop-yarn/staging/vagrant/.staging/job_1479323097233_0004
java.lang.IllegalArgumentException: Network Location is null
	at org.apache.hadoop.net.NodeBase.normalize(NodeBase.java:131)
	at org.apache.hadoop.net.NodeBase.<init>(NodeBase.java:65)
	at org.apache.hadoop.hdfs.DFSUtil.locatedBlocks2Locations(DFSUtil.java:522)
	at org.apache.hadoop.hdfs.DFSUtil.locatedBlocks2Locations(DFSUtil.java:495)
	at org.apache.hadoop.hdfs.DFSClient.getBlockLocations(DFSClient.java:1272)
```

**Comment by zhouhanc** [comment]
This is fixed by setting the value of network in datanodeblockbuf.
