### ISSUE TITLE
Unable to close file exception 

### ISSUE THREAD

**Issue by zhouhanc** [Rice-Comp413-2016/RDFS#80]
Map-Reduce client stacktrace
```

16/11/17 01:53:53 INFO mapred.LocalJobRunner: reduce task executor complete.
16/11/17 01:53:53 WARN mapred.LocalJobRunner: job_local1637994627_0001
java.lang.Exception: java.io.IOException: Unable to close file because the last block does not have enough number of replicas.
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.io.IOException: Unable to close file because the last block does not have enough number of replicas.
	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2306)
	at org.apache.hadoop.hdfs.DFSOutputStream.closeImpl(DFSOutputStream.java:2267)
	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2232)

```

The problem seems to be the client tries to create a file, but the file is never complete. Very detailed 
error message and logic flows can be found here, at Current Issues, No.6

[https://docs.google.com/document/d/1zIigUXavAnhtv-6UvkaW-7-PJfCNNIFVAXTQuKr3vbk/edit](https://docs.google.com/document/d/1zIigUXavAnhtv-6UvkaW-7-PJfCNNIFVAXTQuKr3vbk/edit)

**Comment by Vegetable26** [comment]
Working on this

**Comment by zhouhanc** [comment]
fixed
